### ISSUE TITLE
Enum for Entity/Object Type Codes?

### ISSUE THREAD

**Issue by zaha** [delegateas/XrmDefinitelyTyped#113]
Hi everyone,

is there no enum for the [entity type codes](http://www.dynamicscrm.blog/object-type-codes-cheat-sheet-for-dynamics-365/) being generated by XrmDefinitelyTyped? Was a bit surprise I couldn't find anything.

Can you add this? Would be very much appreciated.

Cheers
Michael

**Comment by TomMalow** [comment]
Hi @zaha 

We don't plan on adding this feature. Entity type codes are not consistent between environments for custom entities. Since we only fetch typings for one environment means that any solution dealing with custom entities is not expected to work as soon as the code is deployed to another environment.

This means that we are only able to handle system entities. We don't like the idea of implement a solution for only a subset of entities. Instead we suggest that you work around type codes as they are not consistent.

What is the case that you are looking to use object type codes?

**Comment by zaha** [comment]
Hi @TomMalow 

I see. I didn't know that. In our environment they happen to be the same as we clone existing environments to create new ones. That's good to know, though.

Well I guess use case is a rather hacky one: We create a layout XML for a grid that requires the object type code and add this as a custom view to a control. Like so:

```
const objectTypeCode = 2; // Contact Type Code
const layoutXml = ("<grid name='resultset' object='" + objectTypeCode +
	"' jump='contact' select='1' icon='1' preview='1'>" +
	"<row name='result' id='contactid'>" +
	"<cell name='fullname' width='125' />" +
	// ..
	"</row>" +
	" </grid>").toLowerCase();        

const destination = Form.getControl("primarycontactid");
destination.addCustomView(viewId, "contact", viewDisplayName, fetchXml, layoutXml, true);
```

**Comment by TomMalow** [comment]
We haven't used `addCustomView` all that much. However, I do have some thoughts on it. Is it at all necessary to add object to the layout xml? If it is necessary then does it have to be exact? wouldn't just writting `0` work?`I have a hard time seeing any reason why the layout xml requires the object type code.

One of my colleagues mentioned that they might have used it and just added `0` instead of the object type code :P

**Comment by zaha** [comment]
Ha, well... that's a thought that hasn't occurred to us yet. 😂 
Getting rid of this completely would of course be ideal. Let me check with my colleague working on that, I'll get back to you when he was able to test it.

**Comment by zaha** [comment]
As it turns out, the attribute can be omitted completely which we do now. Thanks for the tip!

Closing the issue as it became obsolete.
