### ISSUE TITLE
setIsValid is absente

### ISSUE THREAD

**Issue by MaTeMaTuK** [delegateas/XrmDefinitelyTyped#162]
Hi,
formContext.getAttribute(arg).setIsValid(bool, message) function is absente.
Could you please add it?

**Environment**
- D365 Online 
- Tool version: [5.0.0]

**Documentation Link**
https://docs.microsoft.com/en-us/powerapps/developer/model-driven-apps/clientapi/reference/attributes/setisvalid

**Comment by magesoe** [comment]
Added in 5.0.1

**Comment by sergeytunnik** [comment]
This function is only supported by latest D365 9.1 online release.
This is from latest on-prem.
![image](https://user-images.githubusercontent.com/512079/85549432-a7e57000-b628-11ea-8273-a555863bacf5.png)

It should be moved into xrm_ext_9.1-.d.ts if I get it right.
It's pity that there is no 'supported by/since' information in client API docs.

**Comment by TomMalow** [comment]
I guess it is the same with `IsValid`?

**Comment by sergeytunnik** [comment]
Actually no. As it shown on screenshot it properly returns boolean.
If there is validation error on attribute (for example wrong email format) - it will return false. Otherwise it returns true.

**Comment by TomMalow** [comment]
Ah great, didn't spot that.
