### ISSUE TITLE
Form methods after 2011 should not appear in CRM 2011

### ISSUE THREAD

**Issue by magesoe** [delegateas/XrmDefinitelyTyped#17]
Taken from a comment on #16 

The following methods shouldn't be suggested when using CRM 2011.

Introduced in CRM 2013:
Xrm.Utility.isActivityType
Xrm.Page.context.getUserName
Lookup: Xrm.Page.getControl(arg).addPreSearch
Lookup: Xrm.Page.getControl(arg).removePreSearch
"then" method (interface Then) only makes sense after async refresh or save.

Introduced in CRM 2015:
Xrm.Utility.openQuickCreate
Xrm.Page.context.getIsAutoSaveEnabled
Xrm.Page.context.getTimeZoneOffsetMinutes
DateTime: Xrm.Page.getControl(arg).getShowTime
Subgrid: Xrm.Page.getControl(arg).getRelationshipName
Xrm.Page.ui.process.xyz and Xrm.Page.data.process.xyz only makes sense with business process flows. It seems that interfaces with names containing "process" or "stage" are not needed in CRM 2011. And possibly "interface DataModule".

**Comment by lisbyschmidt** [comment]
Thank you for working on this issue so quickly. :)

I still see two minor problems:
- Xrm.Page.ui.process and Xrm.Page.data.process should not be available before CRM 2015.
- Xrm.Page.**getControl**("...").getOptions() should not be available before CRM 2016. (Xrm.Page.**getAttribute**("...").getOptions() is fine!)

**Comment by Tolini** [comment]
I can't seem to find any documentation regarding the Xrm.Page.getControl("...").getOptions() function. Where have you found that it was not available prior to CRM 2016?

**Comment by lisbyschmidt** [comment]
I can't find it in the documentation either! That's why I originally wrote the following in https://github.com/delegateas/XrmDefinitelyTyped/issues/16:
"I believe the method getOptions() should only be available on option-set attributes, not option-set controls."

However, I have since tested it in 2011, 2013, 2015 and 2016/365. It turned out that getOptions() actually exists on controls in 2016/365.
