### ISSUE TITLE
Recommended unit testing framework to work with XrmDefinitelyTyped

### ISSUE THREAD

**Issue by hansgfixed** [delegateas/XrmDefinitelyTyped#188]
I would like to know if anyone has experience with unit testing with XrmDefinitelyTyped? I'm right now trying to get xrm-mock running but I doubt that this will satisfy our needs as it is based on the xrm typings.

Thanks in advance

**Comment by mktange** [comment]
I made a PoC repo some time ago with `xrm-mock` and XDT-like typings, to show that it is possible to use them together as they are now: https://github.com/mktange/xdt-xrm-mock

**Comment by hansgfixed** [comment]
Thanks for your prompt reply.

Unfortunately this repo is using Xrm.Page and does only use one xrm.d.ts. I need the xrmdefinitelytypings when testing the client-side script. I've now so far setup a seperate project for tests but are currently unable to resolve the namespace issues of Xrm (index.d.ts) and Xrm (xrm.d.ts). We have to find a way to incorporate these two.

Example client-side script:

```
let formContext: Form.account.Main.Information;

export module Account {
export function onLoad(executionContext: Xrm.ExecutionContext<any>) {
        try {
            formContext = <Form.account.Main.Information>(executionContext.getFormContext());
             }
        ...
}
```


It can't find the namespace for the Form and ExecutionContext. Any idea how to resolve this? If we can resolve this it looks really promising.

Namespace 'Xrm' has no exported member 'ExecutionContext'.
Cannot find namespace 'Form'.

**Comment by mktange** [comment]
As I mentioned, the repo has "XDT-like typings". It isn't a fully generated set of XDT typings for a CRM instance, but should be just enough to illustrate that they can work together. 

The trick is to not have the `@types/xrm` typings included in your TypeScript compilation, since they aren't directly needed by your code. You should have only have XDT typings included, and then there won't be any issues with types clashing from the two sets of typings.

**Comment by hansgfixed** [comment]
Thanks for the input. I created a seperate project and tried it without the xrm typings but it didn't work. In the regular project it works as expected.
