### ISSUE TITLE
Typing for system views for custom icons and tooltips

### ISSUE THREAD

**Issue by plantoschka** [delegateas/XrmDefinitelyTyped#20]
Dynamics 365 v. 8.2 allows to embed custom icons and tooltips into Views which is a really great feature:
@https://msdn.microsoft.com/en-us/library/gg328457.aspx#BKMK_CustomIcons

It would be great to have Typings for the view definitions.

**Comment by henrikhannemose** [comment]
The way I see it, you need to do three things to add icons to views:

1. Upload icons as web resources.
2. Create a function to be called for each row (`imageproviderfunctionname`).
3. Modify the layoutxml to actually call the function for a given row.

For each of these points, we can do the following:

1. We could maybe create typings for your webresources to help you set the image names to valid values in the function. I have not entirely thought through how this would work. In any case, we do not currently have a need for accessing webresources any other places from TypeScript, so we will not implement this now.
2. We could create an interface to be used for the `imageproviderfunction` accepting two parameters (strings?) and returning an array of two strings.
3. We cannot use typings to help you edit the layoutxml.

Since we are down to possibly creating an interface for a function taking two strings and returning an array of strings, I think you might as well create that yourself. In any case, it is not something that needs to be dynamically generated based on your specific CRM-instance. I am thus closing this suggestion for now (unless you have other ideas as to how we can assist this process with typings).

Keep the suggestions coming! :)

**Comment by henrikhannemose** [comment]
@mktange points out that in addition to generating a typing for the `imageproviderfunction`, we could also dynamically generate typings for:

- Web Resources (that are images)
- LCIDs
- Views

This would be quite helpful when writing the `imageproviderfunction`, as demonstrated in @mktange's example below:

```typescript
// Generated
type WebResourcePic = "new_Hot" | "new_Cold" | "new_Warm";

// Generated
const enum LCID {
    English = 1033,
    French = 1036,
    Danish = 1030,
}

// Generated for all views
interface SomeOpportunityView {
    name_Value: string;
    opportunityratingcode_Value: opportunity_opportunityratingcode;
    estimatedclosedate_Value: Date;
}

// Can be static. Just a helper type for the function the developer needs to define
type TooltipFunc = (rowData: string, lcid: LCID) => [WebResourcePic, string]


// Usage
const myIconTooltipFunc: TooltipFunc = (rowData, lcid) => {
    var tooltip = "";
    var view: SomeOpportunityView = JSON.parse(rowData);
    var colName = view.name_Value;

    switch (lcid) {
        case LCID.Danish:
            return ["new_Hot", "Danish: hej!"];

        case LCID.English:
        default:
            return ["new_Cold", "English: hey!"];
    } 
}
```

I am re-opening this issue for possible implementation of the above suggestions.
