### ISSUE TITLE
Add support for multi-select option sets in D365 9.0

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmDefinitelyTyped#28]
In the July update for Dynamics 365 [multi-select option sets](https://docs.microsoft.com/en-us/dynamics365/get-started/whats-new/customer-engagement/new-in-july-2017-update-for-developers#new-attribute-type-multi-select-option-set) have been introduced. It appears that they have been implemented as an array of enum-values:

> Multi-select option sets supports all the client APIs supported for the option sets attributes and controls; the only difference is that the return value of certain methods will be an array instead of a single value.

Add support to XrmDefinitelyTyped for this new data type.

A corresponding [issue ](https://github.com/delegateas/XrmContext/issues/9)has been created for XrmContext.

**Comment by Tolini** [comment]
Currently when using the 9.0 preview sdk, multiselect attributes have the attribute type Virtual and not their own type, which means we can't tell them apart from the Virtual attributes we don't want.
Once multiselect attributes get their own attribute type they will be supported.

**Comment by bo-stig-christensen** [comment]
@Tolini Any updates on this one? Have you checked a later version of the SDK?
I am using XrmToolkit for server-side model generation, which already has an implementation in place (in a prerelease that I received directly from the author).

**Comment by mottibec** [comment]
I am looking into this for a project at work, 
@Tolini multi-select option set would have an AttributeMetadata of MultiSelectPicklistAttributeMetadata instead of EnumAttributeMetadata, we cloud use that to tell them apart from other virtual attributes we don't want, another option would be using AttributeTypeName that would be equal to "MultiSelectPicklistType". 
[MultiSelectPicklistAttributeMetadata](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.multiselectpicklistattributemetadata?view=dynamics-general-ce-9)

**Comment by Tolini** [comment]
Added in e397eaf6d27f2972c3615a4861b70bc61ffd6381

**Comment by magesoe** [comment]
Merged to master
