### ISSUE TITLE
Latest version of XrmDefinitelyTyped is not generating definitions

### ISSUE THREAD

**Issue by D365Guy** [delegateas/XrmDefinitelyTyped#3]
When I attempt to execute the latest XrmDefinitelyTyped exe using the same config as the previous version  I get an error message Unable to generate TypeScript files: access to path "X" is denied

Where X is path + \WebResources\typings\XRM\_internal\Enum\Folder
Where Folder is the name of the folders of the entities in the solution / entities specified in the config
eg Folder hive_blpu.statecode.d.ts = Entity name hive_blpu.statecode

Any ideas why?

**Comment by d4hines** [comment]
I'm having the same exact issue:
Unable to generate TypeScript files: Access to the path 
'C:\Automations\DevOpsWeb\DevOpsWeb.Assets\typings\XRM\REST\datatel_application.d.ts' is denied.

Since is it looks like it's a file system permission issue thing, I'm making sure I have full access in all folders/sub-folders, and I'll post back here if that works. Did it not do this for previous versions?

**Comment by D365Guy** [comment]
I also have a previous version and this problem doesn't occur. I'm going to continue to use a previous verson till this has been resolved

**Comment by mktange** [comment]
This bug has been fixed with the latest patch update (version 2.1.1).

**Comment by d4hines** [comment]
Thanks a ton!!!

**Comment by D365Guy** [comment]
Much appreciated Martin
