### ISSUE TITLE
unable to connect to 9.x API, online

### ISSUE THREAD

**Issue by lukasbelak** [delegateas/XrmDefinitelyTyped#47]
Hi, could you recompile the solution with newest dlls?
Today I started getting this error:
![xrmtyperr](https://user-images.githubusercontent.com/17293975/34537386-216f570a-f0c0-11e7-898a-2c10f2e8fd69.PNG)

**Comment by bo-stig-christensen** [comment]
I have the same issue since yesterday. The problem is not caused by XrmDefinitelyTyped, although the included SDK should be updated regardless to latest 9.0 :-)

(I actually pulled the repo and replaced the SDK with latest 9.0 temporarily to test)

The issue you are facing is the same as most of us in the new year in many different tools and components. - Microsoft has most likely messed up their v9.0 organization service and various authentication handshakes are going wrong.

Microsoft has at least 4 support tickets (that I am aware of) about this and similar issues. - We just have to give them a bit more time to fix their web services ;-)

**Comment by lukasbelak** [comment]
you could change target framework to .NET 4.6.2 according to: [https://blogs.msdn.microsoft.com/crminthefield/2017/11/08/dynamics-365-monthly-update-october-2017/](url)

A snippet from the article:

_To avoid impact:
Custom Windows clients built utilizing .NET 4.5.2 can be fixed by recompiling on .NET 4.6.2. Versions of .NET 4.6.2 and higher implement a process that will seek the highest possible security transport that the host operating system supports.
If you are unable to do this, you can utilize a registry setting on Windows that will force .NET to utilize the highest possible security standard. Please Note: This is a machine-wide setting and may have undesired affects. It is recommended that you or your customer utilize the method of recompiling to .NET 4.6.2 or higher. The registry settings that will force .NET 4.5.2 to prefer TLS 1.2 machine-wide are documented in the article Microsoft Security Advisory 2960358 in the section "Suggested Actions" under "Manually disable RC4 in TLS on systems running .NET Framework 4.5/4.5.1/4.5.2"_

I tested it with simple console app and it works.

**Comment by gashupl** [comment]
Yes. This might be solution. According to my knowledge 4.5.2 application are actively blocked in Dyn365 CE cloud at this moment...

EDIT: I've downloaded solution source codes, upgraded CRM SDK assemblies to 9.x version and changed target .NET framework to 4.6.2. After recompilation - everything was working correctly.

**Comment by lukasbelak** [comment]
@gashupl  great, could you also update Delegate.XrmDefinitelyTyped package on nuget? Thanks.

**Comment by TomMalow** [comment]
We are in the progress of investigating the issue, and it is as you guys have written. We need to upgrade our XrmDefinitelyTyped to run with .net framework 4.6.2 in order to make use of TLS 1.2 instead of 1.1 which is not supported in Dynamics 9.0.

We are in the progress of updating all our tools to run with 4.6.2 and we will write back when a new version is released of XrmDefinitelyTyped. We expect the new version to be out within a few hours.

**Comment by bo-stig-christensen** [comment]
Yes, this has been confirmed by Microsoft this morning.
They were not supposed to have blocked TLS 1.1 until March as far as I remember from D365 highlights ;-)

Awaiting new version and ready to test :-)

**Comment by TomMalow** [comment]
We have released a new version of XrmDefinitelyTyped, v. 2.5.1. Sorry for the delay. Can you test and see if it solves the issue just to be sure?

Thank you very much @lukasbelak, @bo-stig-christensen, and @gashupl for assisting in solving this issue. We appreciate your interest in our tools :)

**Comment by gashupl** [comment]
The 2.5.1 version seems to be working correctly. Great work guys! :)
