### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by d4hines** [delegateas/XrmDefinitelyTyped#5]
Hello,
I'm sure this is due to my novice status as a developer and complete unfamiliarity with F#, but I can't get the project to build. 
- I'm running VS 2015.
- I've installed F# tools for VS2015 and the Java SDK. 
- I've installed TypeScript globally.
- I went to .paket/ and ran the bootstrapper, then ran .paket/paket.exe (Is that supposed to be part of the build steps? lf so, it would be helpful in the readme for noobs like me)
- I ran Build (Ctrl+Shift+B in VS2015).
The results: 
------ Build started: Project: XrmDefinitelyTyped, Configuration: Debug Any CPU ------
	tsc -p C:\Repos\XrmDefinitelyTyped\src\XrmDefinitelyTyped\Resources
	java -jar C:\Repos\XrmDefinitelyTyped\src\XrmDefinitelyTyped\..\..\tools\closure\compiler.jar --js C:\Repos\XrmDefinitelyTyped\src\XrmDefinitelyTyped\Resources\Dist\dg.xrmquery.rest.js --js_output_file C:\Repos\XrmDefinitelyTyped\src\XrmDefinitelyTyped\Resources\Dist\dg.xrmquery.rest.min.js
EXEC: error : Unable to access jarfile C:\Repos\XrmDefinitelyTyped\src\XrmDefinitelyTyped\..\..\tools\closure\compiler.jar
C:\Repos\XrmDefinitelyTyped\src\XrmDefinitelyTyped\XrmDefinitelyTyped.fsproj(153,5): error MSB3073: The command "java -jar C:\Repos\XrmDefinitelyTyped\src\XrmDefinitelyTyped\..\..\tools\closure\compiler.jar --js C:\Repos\XrmDefinitelyTyped\src\XrmDefinitelyTyped\Resources\Dist\dg.xrmquery.rest.js --js_output_file C:\Repos\XrmDefinitelyTyped\src\XrmDefinitelyTyped\Resources\Dist\dg.xrmquery.rest.min.js" exited with code 1.
Done building project "XrmDefinitelyTyped.fsproj" -- FAILED.

Build FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Now, the cause is obvious: the files the script attempts to access aren't there. But that must mean I'm missing a step or doing one incorrectly (or both). Either explicit instructions for this project or a reference to general instructions on building an F# project would be greatly appreciated.

**Comment by mktange** [comment]
This project is built using [ProjectScaffold](http://fsprojects.github.io/ProjectScaffold/index.html), which in turn uses [FAKE](http://fsharp.github.io/FAKE/) to automate a lot of the build tasks (setup, build, test, docs, nuget package, releases, etc).

Before you can build/run the project from Visual Studio, you need to run `build` from the command-line in the root folder. FAKE handles setting up the project and it's dependencies as needed, before running the actual MSBuild task on the project. But once it has been set up correctly by FAKE, you will be able to build the project using Visual Studio from then on.

Be sure to pull the latest change I just made, since it has a small (but necessary) change to the build script.

**Comment by d4hines** [comment]
Ah! That was the missing info. I followed your instructions (thanks for updating the read.me as well), and everything built and tested successfully. Thanks!
