### ISSUE TITLE
MFA support

### ISSUE THREAD

**Issue by StevenRasmussen** [delegateas/XrmDefinitelyTyped#95]
Hello, 

Do you have any plans to support organizations that require MFA?

Regards,
Steve

**Comment by magesoe** [comment]
This is a topic I would love to have a discussion on, not just for XDT, but for all of our tooling. Right now, we call our tooling with a service user without MFA, since we use them in our build pipeline. Therefore, we have not focused on adding support for it, since we demand that we have access to such a user when working with our clients.

However, I can see a situation where you want to use your own user during development and use a service user in your build pipeline. In such a situation it will be useful to have MFA support.

That said, other issues have higher priority right now, and would love a pull request that implements MFA in a meaningful way, if this is something you need support for urgently.

**Comment by magesoe** [comment]
Seems we have already discussed this on a DAXIF issue. Henrik found a reference to a great solution where an Azure app is used.
https://github.com/delegateas/Daxif/issues/31#issuecomment-431015669

**Comment by StevenRasmussen** [comment]
See PR [#98](https://github.com/delegateas/XrmDefinitelyTyped/pull/98)

**Comment by magesoe** [comment]
Added in version 4.4.0
